SOURCING_CANDIDATES = [
    # ── 실리콘 주방소품 ──────────────────────────────────────────────
    {"id":1,"name":"실리콘 냄비 받침대 5p 세트","related":"업소용 가스레인지","category":"주방소품","channel":"both","competition":{"intensity":21,"top_reviews":143,"rocket_ratio":24},"selling":17900,"sourcing":2600,"logistics":2500,"weight":"0.5kg","keywords_1688":["硅胶锅垫","防烫锅垫","锅架垫 5件"],"customer_fit":True,"fit_reason":"가스레인지 구매 고객이 바로 함께 쓰는 필수품"},
    {"id":2,"name":"실리콘 조리도구 세트 5종","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":35,"top_reviews":289,"rocket_ratio":38},"selling":18900,"sourcing":3200,"logistics":2500,"weight":"0.6kg","keywords_1688":["硅胶厨具套装 5件","炒菜铲勺硅胶","耐高温硅胶厨具"],"customer_fit":True,"fit_reason":"가스레인지·프라이팬 구매 고객 필수 세트"},
    {"id":3,"name":"실리콘 주방 매트 대형 60x40cm","related":"업소용 싱크대","category":"주방소품","channel":"both","competition":{"intensity":28,"top_reviews":198,"rocket_ratio":31},"selling":22900,"sourcing":4000,"logistics":3000,"weight":"1.0kg","keywords_1688":["硅胶厨房垫 大号","防滑餐桌垫","硅胶台垫 60x40"],"customer_fit":True,"fit_reason":"싱크대·작업대 설치 후 위생 매트 수요 즉시 발생"},
    {"id":4,"name":"실리콘 냄비 그립 핸들 커버 2p","related":"업소용 냄비","category":"주방소품","channel":"both","competition":{"intensity":14,"top_reviews":67,"rocket_ratio":16},"selling":12900,"sourcing":1600,"logistics":1500,"weight":"0.2kg","keywords_1688":["硅胶锅把套","防烫锅把手","硅胶锅柄保护套"],"customer_fit":True,"fit_reason":"냄비 구매 시 바로 추가 구매하는 안전 소품"},
    {"id":5,"name":"실리콘 식기 건조 매트 40x30cm","related":"업소용 싱크대","category":"싱크대 용품","channel":"both","competition":{"intensity":31,"top_reviews":312,"rocket_ratio":35},"selling":15900,"sourcing":2800,"logistics":2000,"weight":"0.5kg","keywords_1688":["硅胶沥水垫","碗碟干燥垫","厨房沥水毯"],"customer_fit":True,"fit_reason":"싱크대 주변 필수 위생 용품"},
    {"id":6,"name":"실리콘 밀봉 뚜껑 6종 세트","related":"업소용 냄비","category":"주방소품","channel":"both","competition":{"intensity":22,"top_reviews":156,"rocket_ratio":25},"selling":16900,"sourcing":2500,"logistics":2000,"weight":"0.4kg","keywords_1688":["硅胶密封盖6件套","保鲜盖硅胶","碗盆通用密封盖"],"customer_fit":True,"fit_reason":"냄비·볼 구매 고객의 필수 보관 용품"},
    {"id":7,"name":"실리콘 뒤집개 내열 300도","related":"업소용 프라이팬","category":"조리도구","channel":"both","competition":{"intensity":19,"top_reviews":112,"rocket_ratio":22},"selling":11900,"sourcing":1600,"logistics":1500,"weight":"0.15kg","keywords_1688":["硅胶铲刀 耐高温","不粘锅炒菜铲","硅胶锅铲"],"customer_fit":True,"fit_reason":"프라이팬 구매 고객 필수 도구"},
    {"id":8,"name":"실리콘 국자 주걱 세트 3종","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":26,"top_reviews":178,"rocket_ratio":29},"selling":14900,"sourcing":2200,"logistics":2000,"weight":"0.3kg","keywords_1688":["硅胶汤勺铲3件套","厨房硅胶组合","硅胶炊具套装"],"customer_fit":True,"fit_reason":"조리도구 세트 구매 시 자주 함께 구매"},

    # ── 스테인레스 조리도구 ──────────────────────────────────────────
    {"id":9,"name":"스테인레스 조리도구 6종 세트","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":18,"top_reviews":89,"rocket_ratio":20},"selling":28900,"sourcing":5800,"logistics":2500,"weight":"0.9kg","keywords_1688":["不锈钢厨具套装","厨房用具6件套","炒菜铲勺套装"],"customer_fit":True,"fit_reason":"가스레인지+냄비 구매 고객 대상 업셀링 가능"},
    {"id":10,"name":"스테인레스 볼 3종 세트 18/22/26cm","related":"업소용 싱크대","category":"조리도구","channel":"both","competition":{"intensity":33,"top_reviews":224,"rocket_ratio":37},"selling":24900,"sourcing":5200,"logistics":3000,"weight":"1.3kg","keywords_1688":["不锈钢打蛋盆3件套","厨房搅拌盆","不锈钢料理盆"],"customer_fit":True,"fit_reason":"싱크대·작업대 구매 후 조리도구 세트 구매 유도"},
    {"id":11,"name":"스테인레스 집게 2종 세트 25/30cm","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":16,"top_reviews":54,"rocket_ratio":18},"selling":13900,"sourcing":2000,"logistics":2000,"weight":"0.3kg","keywords_1688":["不锈钢食品夹2件","厨房夹子套装","食品夹 25 30cm"],"customer_fit":True,"fit_reason":"업소용 조리 필수품, 반복 소모성 품목"},
    {"id":12,"name":"스테인레스 계량스푼 5종 세트","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":19,"top_reviews":178,"rocket_ratio":22},"selling":11900,"sourcing":1500,"logistics":1500,"weight":"0.15kg","keywords_1688":["不锈钢量勺5件套","计量匙","烘焙量勺套装"],"customer_fit":True,"fit_reason":"요리 시 필수 계량 도구, 저가 고회전 품목"},
    {"id":13,"name":"스테인레스 거품기 2종 세트 25/30cm","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":24,"top_reviews":143,"rocket_ratio":27},"selling":14900,"sourcing":2200,"logistics":2000,"weight":"0.25kg","keywords_1688":["不锈钢打蛋器2件","厨房打蛋器","手动搅拌器"],"customer_fit":True,"fit_reason":"조리 도구 세트 구매 시 자주 함께 구매"},
    {"id":14,"name":"스테인레스 음식 서빙 집게 30cm","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":27,"top_reviews":211,"rocket_ratio":31},"selling":15900,"sourcing":2400,"logistics":2000,"weight":"0.2kg","keywords_1688":["不锈钢服务夹 30cm","餐厅食品夹","自助餐夹子"],"customer_fit":True,"fit_reason":"식당 오픈 시 반드시 필요한 서빙 도구"},
    {"id":15,"name":"스테인레스 계량컵 세트 250/500/1000ml","related":"업소용 전반","category":"조리도구","channel":"both","competition":{"intensity":21,"top_reviews":134,"rocket_ratio":24},"selling":18900,"sourcing":3800,"logistics":2500,"weight":"0.5kg","keywords_1688":["不锈钢量杯3件套","厨房计量杯","烘焙量水杯"],"customer_fit":True,"fit_reason":"정확한 레시피 재현 필수 도구"},

    # ── 냉장고 용품 ──────────────────────────────────────────────────
    {"id":16,"name":"냉장고 정리 투명 트레이 3단","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":29,"top_reviews":387,"rocket_ratio":35},"selling":15900,"sourcing":2900,"logistics":2000,"weight":"0.7kg","keywords_1688":["冰箱收纳盒","冰箱整理盒 3层","透明冰箱隔板"],"customer_fit":True,"fit_reason":"냉장고 납품 후 정리용품 추가구매 니즈 높음"},
    {"id":17,"name":"냉장고 야채 보관함 투명 대형","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":34,"top_reviews":298,"rocket_ratio":39},"selling":13900,"sourcing":2200,"logistics":2000,"weight":"0.5kg","keywords_1688":["冰箱蔬菜保鲜盒","透明储菜盒","冷藏蔬菜收纳"],"customer_fit":True,"fit_reason":"업소용 냉장고 구매 후 식재료 정리 필수"},
    {"id":18,"name":"냉장고 달걀 케이스 24구 2단","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":18,"top_reviews":89,"rocket_ratio":20},"selling":12900,"sourcing":1800,"logistics":1500,"weight":"0.3kg","keywords_1688":["冰箱鸡蛋收纳盒 双层","24格鸡蛋盒","透明鸡蛋储存盒"],"customer_fit":True,"fit_reason":"달걀을 많이 사용하는 식당 필수 아이템"},
    {"id":19,"name":"냉장고 음료 자동 롤링 정리대","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":41,"top_reviews":356,"rocket_ratio":45},"selling":18900,"sourcing":3800,"logistics":2500,"weight":"0.8kg","keywords_1688":["冰箱饮料整理架","罐装饮料滚动架","冷藏罐装收纳"],"customer_fit":True,"fit_reason":"음료를 판매하는 카페·식당 필수"},
    {"id":20,"name":"진공 밀폐 용기 세트 5종","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":48,"top_reviews":512,"rocket_ratio":52},"selling":29900,"sourcing":6500,"logistics":3000,"weight":"1.5kg","keywords_1688":["真空密封罐5件套","食品密封盒","抽气保鲜盒套装"],"customer_fit":True,"fit_reason":"식재료 신선도 유지 필수, 재구매율 높음"},
    {"id":21,"name":"냉장고 탈취 살균 박스 2p","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":28,"top_reviews":198,"rocket_ratio":32},"selling":16900,"sourcing":3200,"logistics":2000,"weight":"0.3kg","keywords_1688":["冰箱除味盒 2个","冰箱杀菌除臭","活性炭冰箱清洁"],"customer_fit":True,"fit_reason":"업소용 냉장고 위생 관리 필수"},
    {"id":22,"name":"음식 신선도 밀봉 클립 20p 세트","related":"업소용 냉장고","category":"주방소품","channel":"both","competition":{"intensity":12,"top_reviews":67,"rocket_ratio":14},"selling":9900,"sourcing":1200,"logistics":1500,"weight":"0.1kg","keywords_1688":["食品密封夹 20个","保鲜夹套装","零食袋封口夹"],"customer_fit":True,"fit_reason":"저가 고회전 소모품, 반복 구매율 높음"},

    # ── 싱크대/설거지 용품 ──────────────────────────────────────────
    {"id":23,"name":"접이식 싱크대 건조 선반","related":"업소용 싱크대","category":"싱크대 용품","channel":"both","competition":{"intensity":44,"top_reviews":412,"rocket_ratio":48},"selling":22900,"sourcing":4200,"logistics":2500,"weight":"1.1kg","keywords_1688":["折叠沥水架","厨房置物架","水槽沥碗架"],"customer_fit":True,"fit_reason":"싱크대 설치 후 주변 정리용품 수요 즉시 발생"},
    {"id":24,"name":"싱크대 코너 정리 선반 흡착식","related":"업소용 싱크대","category":"싱크대 용품","channel":"both","competition":{"intensity":36,"top_reviews":287,"rocket_ratio":40},"selling":19900,"sourcing":3500,"logistics":2500,"weight":"0.7kg","keywords_1688":["水槽角落置物架","无钉吸盘收纳架","厨房转角架"],"customer_fit":True,"fit_reason":"싱크대 주변 공간 활용 필수 아이템"},
    {"id":25,"name":"주방 세제 디스펜서 벽부착형","related":"업소용 싱크대","category":"싱크대 용품","channel":"both","competition":{"intensity":29,"top_reviews":189,"rocket_ratio":33},"selling":16900,"sourcing":2800,"logistics":2000,"weight":"0.4kg","keywords_1688":["壁挂洗洁精盒","皂液器挂墙","厨房洗碗液分配器"],"customer_fit":True,"fit_reason":"싱크대 설치 후 바로 필요한 위생 소품"},
    {"id":26,"name":"스테인레스 싱크대 망 필터 10p","related":"업소용 싱크대","category":"싱크대 용품","channel":"both","competition":{"intensity":11,"top_reviews":43,"rocket_ratio":13},"selling":9900,"sourcing":1100,"logistics":1500,"weight":"0.1kg","keywords_1688":["不锈钢水槽过滤网 10个","下水道过滤片","厨房排水网"],"customer_fit":True,"fit_reason":"소모성 위생품, 반복 구매 필수"},
    {"id":27,"name":"자동 센서 주방세제 디스펜서","related":"업소용 싱크대","category":"싱크대 용품","channel":"both","competition":{"intensity":39,"top_reviews":312,"rocket_ratio":43},"selling":29900,"sourcing":7500,"logistics":3000,"weight":"0.8kg","keywords_1688":["感应洗洁精机","自动皂液器","智能泡沫洗手机"],"customer_fit":True,"fit_reason":"위생 기준 강화로 자동 디스펜서 수요 증가"},
    {"id":28,"name":"접이식 컵 건조 선반 (벽부착)","related":"업소용 싱크대","category":"싱크대 용품","channel":"coupang","competition":{"intensity":33,"top_reviews":267,"rocket_ratio":37},"selling":18900,"sourcing":3400,"logistics":2500,"weight":"0.9kg","keywords_1688":["杯架沥水架","马克杯晾干架","厨房晾杯架"],"customer_fit":True,"fit_reason":"컵을 많이 사용하는 카페·식당 필수"},
    {"id":29,"name":"배수구 필터 망 원형 10p 세트","related":"업소용 싱크대","category":"위생용품","channel":"both","competition":{"intensity":13,"top_reviews":56,"rocket_ratio":15},"selling":7900,"sourcing":900,"logistics":1500,"weight":"0.05kg","keywords_1688":["下水道过滤网 10个","圆形地漏过滤","厨房排水过滤网"],"customer_fit":True,"fit_reason":"싱크대 필수 소모품, 반복 구매율 최고"},
    {"id":30,"name":"세제 대용량 디스펜서 5L 업소용","related":"업소용 싱크대","category":"싱크대 용품","channel":"coupang","competition":{"intensity":22,"top_reviews":145,"rocket_ratio":26},"selling":19900,"sourcing":4200,"logistics":3000,"weight":"0.8kg","keywords_1688":["大容量洗洁精桶 5L","商用皂液桶","洗碗液储存桶"],"customer_fit":True,"fit_reason":"업소용 대용량 세제 관리 필수"},

    # ── 수납/정리 ────────────────────────────────────────────────────
    {"id":31,"name":"주방 다기능 후크 행거 20p","related":"업소용 작업대","category":"수납/정리","channel":"both","competition":{"intensity":15,"top_reviews":67,"rocket_ratio":18},"selling":13900,"sourcing":1800,"logistics":1500,"weight":"0.3kg","keywords_1688":["厨房挂钩","多功能挂钩 20个","无痕挂钩套装"],"customer_fit":True,"fit_reason":"작업대·선반 구매 시 정리용품 동시 수요"},
    {"id":32,"name":"냄비뚜껑 거치대 스탠드","related":"업소용 냄비","category":"주방소품","channel":"both","competition":{"intensity":12,"top_reviews":34,"rocket_ratio":15},"selling":16900,"sourcing":2200,"logistics":2000,"weight":"0.6kg","keywords_1688":["锅盖架","锅盖收纳架","厨房锅盖置物架"],"customer_fit":True,"fit_reason":"냄비 세트 구매 고객에게 세트 제안 용이"},
    {"id":33,"name":"주방 3단 카운터 정리대","related":"업소용 작업대","category":"수납/정리","channel":"both","competition":{"intensity":38,"top_reviews":312,"rocket_ratio":42},"selling":24900,"sourcing":5000,"logistics":3000,"weight":"1.2kg","keywords_1688":["厨房3层置物架","台面整理架","厨房收纳架 3层"],"customer_fit":True,"fit_reason":"작업대 구매 후 상부 정리대 수요 발생"},
    {"id":34,"name":"주방 벽걸이 선반 스텐 60cm","related":"업소용 작업대","category":"수납/정리","channel":"both","competition":{"intensity":42,"top_reviews":387,"rocket_ratio":46},"selling":29900,"sourcing":6500,"logistics":3500,"weight":"1.5kg","keywords_1688":["不锈钢壁挂架 60cm","厨房墙上搁板","挂墙置物架"],"customer_fit":True,"fit_reason":"주방 벽 공간 활용, 작업대 주변 정리"},
    {"id":35,"name":"주방용 스텐 S-후크 20p","related":"업소용 작업대","category":"수납/정리","channel":"both","competition":{"intensity":9,"top_reviews":28,"rocket_ratio":12},"selling":8900,"sourcing":900,"logistics":1500,"weight":"0.15kg","keywords_1688":["不锈钢S钩 20个","厨房挂钩S型","挂架小挂钩"],"customer_fit":True,"fit_reason":"선반·작업대 구매 시 항상 함께 필요"},
    {"id":36,"name":"쓰레기봉투 정리 홀더 벽부착","related":"업소용 전반","category":"수납/정리","channel":"both","competition":{"intensity":17,"top_reviews":78,"rocket_ratio":20},"selling":11900,"sourcing":1600,"logistics":1500,"weight":"0.2kg","keywords_1688":["壁挂垃圾袋收纳","垃圾袋挂架","厨房垃圾袋整理盒"],"customer_fit":True,"fit_reason":"모든 업소 공통 필수 정리 아이템"},
    {"id":37,"name":"주방 선반 정리대 확장형 2단","related":"업소용 작업대","category":"수납/정리","channel":"both","competition":{"intensity":36,"top_reviews":278,"rocket_ratio":40},"selling":22900,"sourcing":5000,"logistics":3000,"weight":"1.0kg","keywords_1688":["可扩展层架 2层","厨房伸缩架","储物架 可调节"],"customer_fit":True,"fit_reason":"작업대 공간 확장 필수 아이템"},
    {"id":38,"name":"식기류 수납 서랍 정리함 3p","related":"업소용 전반","category":"수납/정리","channel":"both","competition":{"intensity":31,"top_reviews":234,"rocket_ratio":35},"selling":18900,"sourcing":3800,"logistics":2500,"weight":"0.8kg","keywords_1688":["抽屉收纳盒 3件","厨房整理隔断","餐具收纳格"],"customer_fit":True,"fit_reason":"주방 서랍 정리 필수 아이템"},
    {"id":39,"name":"업소용 쌀 보관통 10kg 용량","related":"업소용 냉장고","category":"수납/정리","channel":"coupang","competition":{"intensity":43,"top_reviews":398,"rocket_ratio":47},"selling":29900,"sourcing":7000,"logistics":4000,"weight":"1.8kg","keywords_1688":["储米箱 10kg","密封米桶","防虫防潮储粮桶"],"customer_fit":True,"fit_reason":"쌀을 많이 쓰는 식당 필수 보관 용기"},
    {"id":40,"name":"업소용 양념통 스텐 세트 5종","related":"업소용 가스레인지","category":"수납/정리","channel":"both","competition":{"intensity":27,"top_reviews":198,"rocket_ratio":31},"selling":22900,"sourcing":4800,"logistics":3000,"weight":"1.0kg","keywords_1688":["调料罐不锈钢 5件","厨房调味盒","酱料罐套装"],"customer_fit":True,"fit_reason":"모든 주방 필수 양념 보관 세트"},

    # ── 식기류 ──────────────────────────────────────────────────────
    {"id":41,"name":"스테인레스 식판 트레이 5p","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":26,"top_reviews":178,"rocket_ratio":30},"selling":34900,"sourcing":7200,"logistics":3000,"weight":"1.8kg","keywords_1688":["不锈钢餐盘","食堂托盘 5个","不锈钢方盘套装"],"customer_fit":True,"fit_reason":"식당 오픈 세팅 고객의 필수 구매 품목"},
    {"id":42,"name":"업소용 스텐 숟가락 10p 세트","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":31,"top_reviews":243,"rocket_ratio":35},"selling":19900,"sourcing":4200,"logistics":2500,"weight":"0.8kg","keywords_1688":["不锈钢汤匙 10个","韩式餐匙","餐厅勺子套装"],"customer_fit":True,"fit_reason":"식당 오픈 필수 식기 세트"},
    {"id":43,"name":"업소용 스텐 젓가락 10켤레","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":28,"top_reviews":198,"rocket_ratio":32},"selling":18900,"sourcing":3800,"logistics":2500,"weight":"0.7kg","keywords_1688":["不锈钢筷子 10双","韩式长筷","餐厅筷子套装"],"customer_fit":True,"fit_reason":"식당 오픈 필수 식기, 반복 구매 품목"},
    {"id":44,"name":"업소용 스텐 국그릇 10p 세트","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":35,"top_reviews":312,"rocket_ratio":39},"selling":39900,"sourcing":8500,"logistics":3500,"weight":"2.2kg","keywords_1688":["不锈钢汤碗 10个","韩式汤碗","食堂汤碗套装"],"customer_fit":True,"fit_reason":"한식당 오픈 필수 식기"},
    {"id":45,"name":"업소용 반찬통 원형 스텐 10p","related":"업소용 냉장고","category":"식기류","channel":"coupang","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":26},"selling":29900,"sourcing":6200,"logistics":3000,"weight":"1.5kg","keywords_1688":["不锈钢圆形饭盒 10个","副菜盒套装","小菜盒不锈钢"],"customer_fit":True,"fit_reason":"한식당 반찬 보관 필수 용기"},
    {"id":46,"name":"업소용 원형 쟁반 4p 세트","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":19,"top_reviews":98,"rocket_ratio":22},"selling":24900,"sourcing":5200,"logistics":3000,"weight":"1.3kg","keywords_1688":["圆形托盘 4件套","餐厅圆盘","塑料圆形餐盘"],"customer_fit":True,"fit_reason":"서빙 트레이, 식당 오픈 필수"},
    {"id":47,"name":"업소용 물컵 스텐 10p 세트","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":24,"top_reviews":156,"rocket_ratio":28},"selling":22900,"sourcing":4800,"logistics":2500,"weight":"1.0kg","keywords_1688":["不锈钢水杯 10个","餐厅饮水杯","韩式杯子套装"],"customer_fit":True,"fit_reason":"식당 오픈 필수 식기, 소모성"},
    {"id":48,"name":"업소용 사각 스텐 쟁반 대","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":21,"top_reviews":112,"rocket_ratio":25},"selling":19900,"sourcing":4100,"logistics":2500,"weight":"0.9kg","keywords_1688":["不锈钢方形托盘","餐厅长方盘","厨房备餐盘"],"customer_fit":True,"fit_reason":"서빙·조리 모두 사용하는 필수 아이템"},
    {"id":49,"name":"업소용 보온 식기 세트 3단","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":33,"top_reviews":256,"rocket_ratio":37},"selling":34900,"sourcing":8200,"logistics":3500,"weight":"1.8kg","keywords_1688":["不锈钢保温饭盒 3层","便携保温桶","食堂打饭保温盒"],"customer_fit":True,"fit_reason":"배달·케이터링 업소 필수 보온 용기"},
    {"id":50,"name":"업소용 절임 통 스텐 10L","related":"업소용 냉장고","category":"식기류","channel":"coupang","competition":{"intensity":24,"top_reviews":156,"rocket_ratio":28},"selling":34900,"sourcing":8000,"logistics":4000,"weight":"2.0kg","keywords_1688":["不锈钢腌制桶 10L","商用泡菜桶","发酵桶 带盖"],"customer_fit":True,"fit_reason":"한식당 김치·절임 필수 보관 용기"},

    # ── 조리도구 ─────────────────────────────────────────────────────
    {"id":51,"name":"주방 실리콘 오일 브러시 세트","related":"업소용 프라이팬","category":"조리도구","channel":"both","competition":{"intensity":19,"top_reviews":112,"rocket_ratio":22},"selling":12900,"sourcing":1500,"logistics":1500,"weight":"0.2kg","keywords_1688":["硅胶油刷套装","烧烤刷 耐高温","厨房刷子套装"],"customer_fit":True,"fit_reason":"프라이팬·그릴 고객에게 추가 제안 쉬움"},
    {"id":52,"name":"다용도 스텐 채반 3종 세트","related":"업소용 싱크대","category":"주방소품","channel":"both","competition":{"intensity":41,"top_reviews":467,"rocket_ratio":44},"selling":24900,"sourcing":4800,"logistics":2500,"weight":"1.2kg","keywords_1688":["不锈钢沥水篮","厨房滤网3件套","漏勺套装"],"customer_fit":True,"fit_reason":"싱크대·냄비 구매 고객의 세트 구매 유도 가능"},
    {"id":53,"name":"채소 탈수기 대형 업소용","related":"업소용 싱크대","category":"조리도구","channel":"both","competition":{"intensity":37,"top_reviews":289,"rocket_ratio":41},"selling":23900,"sourcing":4800,"logistics":3000,"weight":"1.0kg","keywords_1688":["蔬菜脱水器 大号","甩干器 商用","沙拉脱水器"],"customer_fit":True,"fit_reason":"채소를 많이 다루는 식당 필수 도구"},
    {"id":54,"name":"마늘 다지기 롤러형","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":23,"top_reviews":178,"rocket_ratio":26},"selling":14900,"sourcing":2400,"logistics":2000,"weight":"0.3kg","keywords_1688":["大蒜切碎器 滚轮","蒜泥器","手动蒜蓉机"],"customer_fit":True,"fit_reason":"한식 요리 필수 도구, 반복 구매 품목"},
    {"id":55,"name":"채소 강판 3면형 스텐","related":"업소용 싱크대","category":"조리도구","channel":"both","competition":{"intensity":27,"top_reviews":198,"rocket_ratio":31},"selling":16900,"sourcing":2800,"logistics":2000,"weight":"0.4kg","keywords_1688":["不锈钢三面刨丝器","蔬菜刨丝板","多功能擦菜器"],"customer_fit":True,"fit_reason":"채소 손질 필수 도구"},
    {"id":56,"name":"요리용 디지털 탐침 온도계","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":32,"top_reviews":245,"rocket_ratio":36},"selling":14900,"sourcing":2600,"logistics":1500,"weight":"0.1kg","keywords_1688":["食品温度计 探针","厨房数字温度计","烤肉温度计"],"customer_fit":True,"fit_reason":"육류·튀김 요리 품질 관리 필수"},
    {"id":57,"name":"업소용 면 집게 스텐 30cm","related":"업소용 가스레인지","category":"조리도구","channel":"coupang","competition":{"intensity":14,"top_reviews":56,"rocket_ratio":17},"selling":11900,"sourcing":1600,"logistics":1500,"weight":"0.15kg","keywords_1688":["不锈钢面条夹 30cm","拉面夹","厨房长夹"],"customer_fit":True,"fit_reason":"면 요리 업소 필수 도구"},
    {"id":58,"name":"달걀 분리기 슬라이서 세트","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":16,"top_reviews":78,"rocket_ratio":19},"selling":11900,"sourcing":1500,"logistics":1500,"weight":"0.15kg","keywords_1688":["鸡蛋分离器 切蛋器","蛋清蛋黄分离","鸡蛋切片器"],"customer_fit":True,"fit_reason":"달걀을 많이 사용하는 식당 시간 절약 도구"},
    {"id":59,"name":"업소용 도마 항균 2종 세트","related":"업소용 싱크대","category":"조리도구","channel":"both","competition":{"intensity":42,"top_reviews":398,"rocket_ratio":46},"selling":27900,"sourcing":6500,"logistics":3500,"weight":"1.5kg","keywords_1688":["抗菌砧板 2件套","厨房切菜板","PE塑料菜板"],"customer_fit":True,"fit_reason":"조리 위생 필수, 육류/채소 분리 사용"},
    {"id":60,"name":"업소용 색상별 HACCP 도마 3p","related":"업소용 싱크대","category":"조리도구","channel":"both","competition":{"intensity":33,"top_reviews":267,"rocket_ratio":37},"selling":24900,"sourcing":5500,"logistics":3000,"weight":"1.0kg","keywords_1688":["塑料砧板 彩色3件","HACCP切菜板","生熟分离菜板"],"customer_fit":True,"fit_reason":"HACCP 식품 위생 관리 필수 도구"},

    # ── 위생/청소 ─────────────────────────────────────────────────────
    {"id":61,"name":"업소용 방수 앞치마 긴 형","related":"업소용 전반","category":"주방 의류","channel":"coupang","competition":{"intensity":38,"top_reviews":298,"rocket_ratio":42},"selling":19900,"sourcing":3500,"logistics":2000,"weight":"0.4kg","keywords_1688":["防水围裙 长款","厨房围裙 加厚","餐厅防油围裙"],"customer_fit":True,"fit_reason":"자영업자·식당 사장님이 반드시 필요로 하는 품목"},
    {"id":62,"name":"주방 위생 비닐 장갑 100p","related":"업소용 전반","category":"위생용품","channel":"coupang","competition":{"intensity":44,"top_reviews":567,"rocket_ratio":48},"selling":8900,"sourcing":1500,"logistics":1500,"weight":"0.2kg","keywords_1688":["一次性手套 100个","食品级塑料手套","厨房薄膜手套"],"customer_fit":True,"fit_reason":"소모성 위생품, 높은 반복 구매"},
    {"id":63,"name":"극세사 주방 행주 10p 세트","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":39,"top_reviews":423,"rocket_ratio":43},"selling":12900,"sourcing":2200,"logistics":2000,"weight":"0.5kg","keywords_1688":["超细纤维厨房抹布 10条","吸水毛巾","厨房清洁布"],"customer_fit":True,"fit_reason":"소모성 위생품, 반복 구매 필수"},
    {"id":64,"name":"미끄럼 방지 주방 매트 120x45cm","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":46,"top_reviews":489,"rocket_ratio":50},"selling":29900,"sourcing":7000,"logistics":4000,"weight":"2.0kg","keywords_1688":["防滑厨房地垫 大号","厨房地毯","防疲劳脚垫 120x45"],"customer_fit":True,"fit_reason":"장시간 서있는 조리사 필수 안전 아이템"},
    {"id":65,"name":"업소용 고무 손잡이 수세미 세트","related":"업소용 싱크대","category":"위생용품","channel":"both","competition":{"intensity":21,"top_reviews":134,"rocket_ratio":24},"selling":11900,"sourcing":1800,"logistics":1500,"weight":"0.2kg","keywords_1688":["橡胶柄锅刷套装","厨房清洁刷","去污锅刷"],"customer_fit":True,"fit_reason":"싱크대·냄비 구매 후 필수 세척 도구"},
    {"id":66,"name":"바닥 청소 스퀴지 대형","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":28,"top_reviews":187,"rocket_ratio":32},"selling":15900,"sourcing":2800,"logistics":2500,"weight":"0.6kg","keywords_1688":["地板刮水器 大号","橡胶水刮板","厨房地板清洁刮"],"customer_fit":True,"fit_reason":"업소 바닥 청소 필수 도구"},
    {"id":67,"name":"업소용 일회용 위생모 100p","related":"업소용 전반","category":"위생용품","channel":"coupang","competition":{"intensity":18,"top_reviews":89,"rocket_ratio":21},"selling":9900,"sourcing":1500,"logistics":1500,"weight":"0.2kg","keywords_1688":["一次性厨师帽 100个","无纺布厨房帽","餐饮卫生帽"],"customer_fit":True,"fit_reason":"위생 규정 필수 소모품"},
    {"id":68,"name":"비닐 위생장갑 무분말 100p","related":"업소용 전반","category":"위생용품","channel":"coupang","competition":{"intensity":47,"top_reviews":534,"rocket_ratio":51},"selling":9900,"sourcing":1800,"logistics":1500,"weight":"0.15kg","keywords_1688":["无粉丁腈手套 100个","食品级防护手套","一次性无粉手套"],"customer_fit":True,"fit_reason":"위생 필수 소모품, 최고 반복 구매율"},
    {"id":69,"name":"주방 청소 시트형 클리너 30p","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":29,"top_reviews":198,"rocket_ratio":33},"selling":12900,"sourcing":2300,"logistics":2000,"weight":"0.3kg","keywords_1688":["厨房清洁湿巾 30片","油污清洁纸","多功能厨房擦"],"customer_fit":True,"fit_reason":"빠른 주방 청소 필수 소모품"},
    {"id":70,"name":"기름때 제거 스프레이 브러시","related":"업소용 가스레인지","category":"위생용품","channel":"both","competition":{"intensity":32,"top_reviews":234,"rocket_ratio":36},"selling":14900,"sourcing":2600,"logistics":2000,"weight":"0.3kg","keywords_1688":["厨房油污清洁刷","油烟机清洗刷","喷水刷 厨房"],"customer_fit":True,"fit_reason":"가스레인지 주변 기름때 청소 필수"},

    # ── 포장/랩 용품 ─────────────────────────────────────────────────
    {"id":71,"name":"업소용 대형 밀봉 랩 커터 세트","related":"업소용 냉장고","category":"포장용품","channel":"coupang","competition":{"intensity":35,"top_reviews":312,"rocket_ratio":39},"selling":16900,"sourcing":3200,"logistics":2500,"weight":"0.8kg","keywords_1688":["保鲜膜 商用大卷+切割盒","厨房保鲜膜","商用包装膜"],"customer_fit":True,"fit_reason":"냉장고·작업대 구매 고객의 필수 보관 용품"},
    {"id":72,"name":"대형 지퍼백 50p 업소용","related":"업소용 냉장고","category":"포장용품","channel":"coupang","competition":{"intensity":29,"top_reviews":234,"rocket_ratio":33},"selling":12900,"sourcing":2300,"logistics":2000,"weight":"0.3kg","keywords_1688":["大号密封袋 50个","食品密封袋","冷冻保鲜袋"],"customer_fit":True,"fit_reason":"식재료 보관 필수 소모품"},
    {"id":73,"name":"일회용 배달 용기 직사각 50p","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":41,"top_reviews":389,"rocket_ratio":45},"selling":14900,"sourcing":3100,"logistics":2500,"weight":"0.5kg","keywords_1688":["一次性餐盒 50个","外卖打包盒","食品容器套装"],"customer_fit":True,"fit_reason":"배달·포장 식당 필수 소모품"},
    {"id":74,"name":"식품용 날짜 라벨 스티커 200p","related":"업소용 냉장고","category":"포장용품","channel":"both","competition":{"intensity":17,"top_reviews":78,"rocket_ratio":20},"selling":9900,"sourcing":1300,"logistics":1500,"weight":"0.1kg","keywords_1688":["食品标签贴纸 200个","日期标签","保质期标签"],"customer_fit":True,"fit_reason":"HACCP 식품 관리 필수 소모품"},
    {"id":75,"name":"업소용 알루미늄 호일 대형 50m","related":"업소용 가스레인지","category":"포장용품","channel":"coupang","competition":{"intensity":38,"top_reviews":345,"rocket_ratio":42},"selling":14900,"sourcing":3200,"logistics":2500,"weight":"0.8kg","keywords_1688":["铝箔纸 商用大卷 50m","厨房锡纸","烤箱锡纸"],"customer_fit":True,"fit_reason":"구이·오븐 요리 업소 필수 소모품"},
    {"id":76,"name":"음식물 처리 비닐봉투 200p","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":36,"top_reviews":312,"rocket_ratio":40},"selling":9900,"sourcing":1800,"logistics":1500,"weight":"0.4kg","keywords_1688":["食物垃圾袋 200个","厨余垃圾袋","厨房专用垃圾袋"],"customer_fit":True,"fit_reason":"소모성 위생품, 높은 반복 구매"},
    {"id":77,"name":"비닐 포장 랩 거치대 벽부착","related":"업소용 전반","category":"수납/정리","channel":"both","competition":{"intensity":14,"top_reviews":56,"rocket_ratio":17},"selling":14900,"sourcing":2400,"logistics":2000,"weight":"0.3kg","keywords_1688":["保鲜膜挂架 壁挂","厨房膜架","铝箔纸座 墙挂"],"customer_fit":True,"fit_reason":"작업대·카운터 공간 절약 아이템"},
    {"id":78,"name":"업소용 음식 덮개 망 커버 3종","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":17,"top_reviews":78,"rocket_ratio":20},"selling":13900,"sourcing":2200,"logistics":2000,"weight":"0.4kg","keywords_1688":["食物防尘罩 3件套","纱网食物罩","防蝇菜罩"],"customer_fit":True,"fit_reason":"식품 위생 관리 필수, 여름철 수요 급증"},

    # ── 가스레인지/화구 용품 ────────────────────────────────────────
    {"id":79,"name":"냄비 받침 링 원형 스텐 2p","related":"업소용 가스레인지","category":"주방소품","channel":"both","competition":{"intensity":16,"top_reviews":67,"rocket_ratio":19},"selling":12900,"sourcing":1800,"logistics":2000,"weight":"0.4kg","keywords_1688":["炉灶支架圈 2个","灶台锅架","不锈钢锅圈"],"customer_fit":True,"fit_reason":"가스레인지 구매 시 함께 필요한 안전 소품"},
    {"id":80,"name":"가스레인지 보호 매트 3p","related":"업소용 가스레인지","category":"주방소품","channel":"both","competition":{"intensity":23,"top_reviews":156,"rocket_ratio":27},"selling":14900,"sourcing":2400,"logistics":2000,"weight":"0.4kg","keywords_1688":["煤气灶保护垫 3个","灶台防污垫","灶眼盖板"],"customer_fit":True,"fit_reason":"가스레인지 오염 방지 필수 소품"},
    {"id":81,"name":"업소용 철판 그리들 대형 40cm","related":"업소용 가스레인지","category":"조리도구","channel":"coupang","competition":{"intensity":39,"top_reviews":312,"rocket_ratio":43},"selling":39900,"sourcing":8500,"logistics":4000,"weight":"2.5kg","keywords_1688":["铸铁烤盘 大号 40cm","商用煎板","铁板烧烤盘"],"customer_fit":True,"fit_reason":"고기·해산물 요리 업소 필수 조리 도구"},
    {"id":82,"name":"인덕션 호환 어댑터 플레이트","related":"업소용 가스레인지","category":"주방소품","channel":"both","competition":{"intensity":34,"top_reviews":267,"rocket_ratio":38},"selling":24900,"sourcing":5500,"logistics":3000,"weight":"1.2kg","keywords_1688":["电磁炉导热板","感应炉适配器","导磁片 不锈钢"],"customer_fit":True,"fit_reason":"인덕션 사용 업소의 냄비 호환성 문제 해결"},
    {"id":83,"name":"업소용 냉각 와이어 선반 40x30cm","related":"업소용 가스레인지","category":"주방소품","channel":"both","competition":{"intensity":29,"top_reviews":189,"rocket_ratio":33},"selling":18900,"sourcing":3800,"logistics":2500,"weight":"0.7kg","keywords_1688":["冷却网架 40x30","烤箱冷却架","蛋糕晾凉架"],"customer_fit":True,"fit_reason":"베이킹·튀김 후 냉각 필수 도구"},

    # ── 기타 주방 소품 ──────────────────────────────────────────────
    {"id":84,"name":"업소용 방수 디지털 타이머","related":"업소용 가스레인지","category":"주방소품","channel":"both","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":26},"selling":13900,"sourcing":2200,"logistics":1500,"weight":"0.1kg","keywords_1688":["防水厨房计时器","数字烹饪定时器","商用厨房定时器"],"customer_fit":True,"fit_reason":"조리 시간 관리 필수 도구"},
    {"id":85,"name":"주방 디지털 저울 5kg 업소용","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":45,"top_reviews":512,"rocket_ratio":49},"selling":24900,"sourcing":5800,"logistics":2500,"weight":"0.5kg","keywords_1688":["厨房电子秤 5kg","商用精准称","食品克重秤"],"customer_fit":True,"fit_reason":"식재료 계량 필수 도구, 모든 업소 공통"},
    {"id":86,"name":"주방 걸이형 두루마리 휴지 홀더","related":"업소용 전반","category":"수납/정리","channel":"both","competition":{"intensity":19,"top_reviews":102,"rocket_ratio":22},"selling":11900,"sourcing":1700,"logistics":1500,"weight":"0.25kg","keywords_1688":["壁挂卷纸架","厨房纸巾架","纸巾座 挂墙"],"customer_fit":True,"fit_reason":"주방 필수 비품, 모든 업소 공통"},
    {"id":87,"name":"주방 스마트 온습도계 벽부착","related":"업소용 냉장고","category":"주방소품","channel":"both","competition":{"intensity":37,"top_reviews":289,"rocket_ratio":41},"selling":16900,"sourcing":3500,"logistics":2000,"weight":"0.1kg","keywords_1688":["厨房温湿度计 壁挂","数字温湿度仪","食品储存温度监测"],"customer_fit":True,"fit_reason":"식품 위생법 기준 온도 관리 필수"},
    {"id":88,"name":"업소용 짤주머니 세트 실리콘 10p","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":18,"top_reviews":89,"rocket_ratio":21},"selling":14900,"sourcing":2400,"logistics":2000,"weight":"0.3kg","keywords_1688":["硅胶裱花袋 10个","反复使用裱花袋","糕点奶油袋"],"customer_fit":True,"fit_reason":"디저트·제과 카페 필수 도구"},
    {"id":89,"name":"업소용 반죽 스크레이퍼 세트 3p","related":"업소용 작업대","category":"조리도구","channel":"both","competition":{"intensity":14,"top_reviews":56,"rocket_ratio":17},"selling":11900,"sourcing":1600,"logistics":1500,"weight":"0.15kg","keywords_1688":["面团刮板 3件","烘焙刮板套装","厨房刮刀"],"customer_fit":True,"fit_reason":"제과·제빵 업소 필수 도구"},
    {"id":90,"name":"체중 측정 정량 국자 세트 3종","related":"업소용 가스레인지","category":"조리도구","channel":"both","competition":{"intensity":17,"top_reviews":78,"rocket_ratio":20},"selling":16900,"sourcing":3000,"logistics":2000,"weight":"0.3kg","keywords_1688":["定量汤勺 3件套","厨房份量汤勺","计量汤匙套装"],"customer_fit":True,"fit_reason":"레시피 표준화 필수 도구"},

    # ── 카페/음료 전용 ───────────────────────────────────────────────
    {"id":91,"name":"업소용 커피 탬퍼 홀더 탬핑 매트 세트","related":"업소용 전반","category":"주방소품","channel":"coupang","competition":{"intensity":23,"top_reviews":134,"rocket_ratio":27},"selling":19900,"sourcing":4200,"logistics":2500,"weight":"0.4kg","keywords_1688":["咖啡填压器支架+填压垫","浓缩咖啡站","意式咖啡布粉座"],"customer_fit":True,"fit_reason":"카페 오픈 필수 커피 도구 세트"},
    {"id":92,"name":"자동 설탕 시럽 디스펜서","related":"업소용 전반","category":"주방기기","channel":"coupang","competition":{"intensity":26,"top_reviews":167,"rocket_ratio":30},"selling":24900,"sourcing":5800,"logistics":2500,"weight":"0.6kg","keywords_1688":["自动糖浆机","饮品店糖浆架","调味料自动泵"],"customer_fit":True,"fit_reason":"카페·음료 업소 효율 향상 필수"},
    {"id":93,"name":"믹서기 청소 솔 세트","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":13,"top_reviews":45,"rocket_ratio":16},"selling":11900,"sourcing":1600,"logistics":1500,"weight":"0.15kg","keywords_1688":["搅拌机清洁刷套装","厨房清洁刷","奶泡机清洗刷"],"customer_fit":True,"fit_reason":"믹서기·블렌더 사용 업소 청소 필수"},

    # ── 분식/한식 전용 ───────────────────────────────────────────────
    {"id":94,"name":"업소용 소시지 어묵 집게 30cm","related":"업소용 가스레인지","category":"조리도구","channel":"coupang","competition":{"intensity":12,"top_reviews":34,"rocket_ratio":15},"selling":11900,"sourcing":1600,"logistics":1500,"weight":"0.15kg","keywords_1688":["热狗夹 大号 30cm","鱼饼夹","关东煮夹子"],"customer_fit":True,"fit_reason":"분식점·편의점형 업소 필수 도구"},
    {"id":95,"name":"업소용 김밥 틀 세트 5구","related":"업소용 작업대","category":"조리도구","channel":"coupang","competition":{"intensity":21,"top_reviews":123,"rocket_ratio":25},"selling":19900,"sourcing":4200,"logistics":2500,"weight":"0.5kg","keywords_1688":["紫菜卷饭模具 5孔","寿司饭团模具","韩式紫菜包饭工具"],"customer_fit":True,"fit_reason":"분식·도시락 업소 필수 성형 도구"},

    # ── 홀/서비스 용품 ──────────────────────────────────────────────
    {"id":96,"name":"업소용 서빙 트롤리 3단 스텐","related":"업소용 전반","category":"주방기기","channel":"coupang","competition":{"intensity":38,"top_reviews":289,"rocket_ratio":42},"selling":49900,"sourcing":15000,"logistics":5000,"weight":"5.0kg","keywords_1688":["不锈钢送餐车 3层","餐厅服务推车","商用餐车"],"customer_fit":True,"fit_reason":"식당 서빙 효율 향상 필수"},
    {"id":97,"name":"업소용 테이블 번호 스탠드 10p","related":"업소용 전반","category":"주방소품","channel":"coupang","competition":{"intensity":16,"top_reviews":67,"rocket_ratio":19},"selling":14900,"sourcing":2500,"logistics":2000,"weight":"0.4kg","keywords_1688":["餐桌号码牌 10个","桌号立牌","不锈钢号码架"],"customer_fit":True,"fit_reason":"식당 오픈 필수 비품"},

    # ── 진공/포장 기기 ──────────────────────────────────────────────
    {"id":98,"name":"업소용 소형 진공 포장기","related":"업소용 냉장고","category":"주방기기","channel":"coupang","competition":{"intensity":51,"top_reviews":612,"rocket_ratio":55},"selling":49900,"sourcing":14000,"logistics":3500,"weight":"1.5kg","keywords_1688":["小型真空封口机","商用食品真空机","家用封口机"],"customer_fit":True,"fit_reason":"식재료 신선도 관리·포장 판매 필수"},

    # ── 전선/정리 ───────────────────────────────────────────────────
    {"id":99,"name":"주방 전선 정리 케이블 홀더 10p","related":"업소용 전반","category":"수납/정리","channel":"both","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":26},"selling":9900,"sourcing":1300,"logistics":1500,"weight":"0.1kg","keywords_1688":["厨房线夹 10个","电线固定夹","桌面理线器"],"customer_fit":True,"fit_reason":"주방 전기기기 선 정리 필수"},
    {"id":100,"name":"업소용 물티슈 케이스 벽부착형","related":"업소용 전반","category":"수납/정리","channel":"both","competition":{"intensity":19,"top_reviews":89,"rocket_ratio":22},"selling":11900,"sourcing":1700,"logistics":1500,"weight":"0.2kg","keywords_1688":["壁挂湿巾盒","抽纸架 挂墙","厨房纸巾座"],"customer_fit":True,"fit_reason":"모든 업소 필수 위생 비품"},

    # ── 제과/제빵 도구 ──────────────────────────────────────────────
    {"id":101,"name":"실리콘 베이킹 매트 40x30cm 2p","related":"업소용 오븐","category":"제과/제빵","channel":"both","competition":{"intensity":32,"top_reviews":256,"rocket_ratio":36},"selling":19900,"sourcing":3800,"logistics":2500,"weight":"0.6kg","keywords_1688":["硅胶烘焙垫 40x30","防粘烤垫","硅胶烤盘垫 2个"],"customer_fit":True,"fit_reason":"오븐·베이킹 업소 필수 소모품"},
    {"id":102,"name":"케이크 회전 데코 스탠드 알루미늄","related":"업소용 전반","category":"제과/제빵","channel":"both","competition":{"intensity":27,"top_reviews":178,"rocket_ratio":31},"selling":24900,"sourcing":5500,"logistics":3000,"weight":"0.8kg","keywords_1688":["铝合金转台","蛋糕裱花台","旋转裱花托盘"],"customer_fit":True,"fit_reason":"케이크 전문점·카페 필수 데코 도구"},
    {"id":103,"name":"파이핑 깍지 세트 20종","related":"업소용 전반","category":"제과/제빵","channel":"both","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":25},"selling":14900,"sourcing":2600,"logistics":2000,"weight":"0.3kg","keywords_1688":["裱花嘴套装 20个","蛋糕裱花工具","奶油花嘴"],"customer_fit":True,"fit_reason":"제과·디저트 카페 필수 도구"},
    {"id":104,"name":"케이크 오프셋 스패튤라 3종","related":"업소용 전반","category":"제과/제빵","channel":"both","competition":{"intensity":19,"top_reviews":98,"rocket_ratio":22},"selling":16900,"sourcing":3000,"logistics":2000,"weight":"0.25kg","keywords_1688":["奶油刮刀 弯刀 3件","蛋糕抹刀","裱花刮板"],"customer_fit":True,"fit_reason":"케이크 아이싱 필수 도구"},
    {"id":105,"name":"머핀 쿠키 틀 12구 2p 세트","related":"업소용 오븐","category":"제과/제빵","channel":"both","competition":{"intensity":36,"top_reviews":312,"rocket_ratio":40},"selling":22900,"sourcing":4800,"logistics":2500,"weight":"0.9kg","keywords_1688":["马芬蛋糕模 12孔 2个","烤箱饼干模具","不粘烤盘"],"customer_fit":True,"fit_reason":"제과 업소 기본 틀 세트"},
    {"id":106,"name":"밀대 반죽 두께 가이드 세트","related":"업소용 작업대","category":"제과/제빵","channel":"both","competition":{"intensity":14,"top_reviews":67,"rocket_ratio":17},"selling":13900,"sourcing":2200,"logistics":2000,"weight":"0.4kg","keywords_1688":["擀面杖 厚度导轨套装","烘焙擀面棒","面团擀面工具"],"customer_fit":True,"fit_reason":"균일한 반죽 두께 필수 도구"},
    {"id":107,"name":"케이크 랩핑 비닐 OPP 50p","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":18,"top_reviews":89,"rocket_ratio":21},"selling":11900,"sourcing":1800,"logistics":1500,"weight":"0.2kg","keywords_1688":["蛋糕包装膜 50个","OPP透明包装袋","烘焙包装袋"],"customer_fit":True,"fit_reason":"제과 포장 필수 소모품"},
    {"id":108,"name":"실리콘 초콜릿 몰드 24구","related":"업소용 전반","category":"제과/제빵","channel":"both","competition":{"intensity":23,"top_reviews":145,"rocket_ratio":26},"selling":12900,"sourcing":1900,"logistics":1500,"weight":"0.2kg","keywords_1688":["硅胶巧克力模具 24格","糖果模具","冰格巧克力"],"customer_fit":True,"fit_reason":"초콜릿·젤리 디저트 업소 필수"},
    {"id":109,"name":"쿠키 커터 세트 10종 스텐","related":"업소용 전반","category":"제과/제빵","channel":"both","competition":{"intensity":17,"top_reviews":78,"rocket_ratio":20},"selling":14900,"sourcing":2400,"logistics":2000,"weight":"0.3kg","keywords_1688":["不锈钢饼干切模 10件","曲奇饼干模具","糕点切模"],"customer_fit":True,"fit_reason":"쿠키·스콘 업소 다양한 모양 제작 필수"},
    {"id":110,"name":"파운드 케이크 틀 스텐 3종","related":"업소용 오븐","category":"제과/제빵","channel":"both","competition":{"intensity":21,"top_reviews":112,"rocket_ratio":24},"selling":18900,"sourcing":3600,"logistics":2500,"weight":"0.7kg","keywords_1688":["磅蛋糕模具 不锈钢 3件","吐司模具","面包烤模"],"customer_fit":True,"fit_reason":"파운드케이크·식빵 업소 필수 틀"},

    # ── 카페/음료 전용 ──────────────────────────────────────────────
    {"id":111,"name":"스테인레스 밀크 피처 2p 350/600ml","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":29,"top_reviews":213,"rocket_ratio":33},"selling":18900,"sourcing":3800,"logistics":2500,"weight":"0.5kg","keywords_1688":["不锈钢拉花缸 2件 350 600","奶泡壶","咖啡拉花杯"],"customer_fit":True,"fit_reason":"카페 라떼아트 필수 도구"},
    {"id":112,"name":"커피 드립 서버 유리 600ml","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":34,"top_reviews":267,"rocket_ratio":38},"selling":19900,"sourcing":4200,"logistics":2500,"weight":"0.4kg","keywords_1688":["咖啡分享壶 玻璃 600ml","手冲咖啡壶","滴滤咖啡服务壶"],"customer_fit":True,"fit_reason":"핸드드립 카페 필수 서버"},
    {"id":113,"name":"커피 드립 필터 페이퍼 V60 100p","related":"업소용 전반","category":"카페용품","channel":"coupang","competition":{"intensity":38,"top_reviews":398,"rocket_ratio":42},"selling":8900,"sourcing":1500,"logistics":1500,"weight":"0.1kg","keywords_1688":["V60咖啡滤纸 100张","手冲过滤纸","圆锥形滤纸"],"customer_fit":True,"fit_reason":"드립 카페 필수 소모품, 재구매율 최고"},
    {"id":114,"name":"아이스크림 스쿱 트리거형 스텐","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":16,"top_reviews":78,"rocket_ratio":19},"selling":14900,"sourcing":2600,"logistics":2000,"weight":"0.2kg","keywords_1688":["冰淇淋勺 弹簧式","挖球器 不锈钢","冰激凌挖勺"],"customer_fit":True,"fit_reason":"아이스크림·팥빙수 업소 필수"},
    {"id":115,"name":"음료 쉐이커 스텐 800ml","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":26},"selling":16900,"sourcing":3200,"logistics":2000,"weight":"0.35kg","keywords_1688":["不锈钢摇酒壶 800ml","奶茶摇摇杯","调酒器"],"customer_fit":True,"fit_reason":"버블티·스무디 카페 필수 도구"},
    {"id":116,"name":"버블티 대형 스트로우 200p","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":33,"top_reviews":256,"rocket_ratio":37},"selling":9900,"sourcing":1800,"logistics":1500,"weight":"0.3kg","keywords_1688":["珍珠奶茶吸管 200根","大口径吸管","粗吸管 彩色"],"customer_fit":True,"fit_reason":"음료 카페 필수 소모품"},
    {"id":117,"name":"시럽 계량 펌프 표준형 3p","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":19,"top_reviews":102,"rocket_ratio":22},"selling":13900,"sourcing":2400,"logistics":2000,"weight":"0.2kg","keywords_1688":["糖浆泵 标准型 3个","咖啡糖浆配件","饮品店定量泵"],"customer_fit":True,"fit_reason":"시럽·소스 정량 사용 필수"},
    {"id":118,"name":"음료 장식 픽 꼬치 100p","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":11,"top_reviews":45,"rocket_ratio":14},"selling":7900,"sourcing":900,"logistics":1500,"weight":"0.05kg","keywords_1688":["饮品装饰签 100根","水果串签","鸡尾酒装饰牙签"],"customer_fit":True,"fit_reason":"음료 데코 필수 소모품"},
    {"id":119,"name":"커피 그라인더 청소 솔 세트 5p","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":13,"top_reviews":56,"rocket_ratio":16},"selling":11900,"sourcing":1700,"logistics":1500,"weight":"0.1kg","keywords_1688":["咖啡磨豆机清洁刷 5件","研磨机刷子","磨粉机清洗刷"],"customer_fit":True,"fit_reason":"그라인더 정기 청소 필수 도구"},
    {"id":120,"name":"콜드브루 더치커피 서버 유리 1L","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":28,"top_reviews":189,"rocket_ratio":32},"selling":29900,"sourcing":6800,"logistics":3000,"weight":"0.7kg","keywords_1688":["冷萃咖啡壶 玻璃 1L","荷兰咖啡滴漏壶","冷泡咖啡器"],"customer_fit":True,"fit_reason":"스페셜티 카페 프리미엄 음료 제공"},

    # ── 냉동/냉장 전용 ──────────────────────────────────────────────
    {"id":121,"name":"업소용 얼음 틀 대형 48구 2p","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":21,"top_reviews":134,"rocket_ratio":24},"selling":13900,"sourcing":2200,"logistics":2000,"weight":"0.4kg","keywords_1688":["制冰格 大号 48格 2个","冰块模具","硅胶冰格"],"customer_fit":True,"fit_reason":"음료 업소 얼음 제조 필수"},
    {"id":122,"name":"아이스 통 스텐 8L 집게 세트","related":"업소용 냉장고","category":"카페용품","channel":"coupang","competition":{"intensity":24,"top_reviews":156,"rocket_ratio":28},"selling":29900,"sourcing":6800,"logistics":3500,"weight":"1.5kg","keywords_1688":["不锈钢冰桶 8L+冰夹","商用冰桶","酒吧冰桶套装"],"customer_fit":True,"fit_reason":"음료 업소 얼음 보관 필수"},
    {"id":123,"name":"냉동 보관백 지퍼 2L 50p","related":"업소용 냉장고","category":"포장용품","channel":"coupang","competition":{"intensity":32,"top_reviews":245,"rocket_ratio":36},"selling":11900,"sourcing":2100,"logistics":2000,"weight":"0.3kg","keywords_1688":["冷冻保鲜袋 2L 50个","冰箱密封袋","食品冷冻袋"],"customer_fit":True,"fit_reason":"식재료 냉동 보관 필수 소모품"},
    {"id":124,"name":"재사용 아이스팩 대형 10p","related":"업소용 냉장고","category":"포장용품","channel":"both","competition":{"intensity":29,"top_reviews":198,"rocket_ratio":33},"selling":14900,"sourcing":2800,"logistics":2500,"weight":"1.0kg","keywords_1688":["可重复使用冰袋 大号 10个","保冷袋","蓝冰冰盒"],"customer_fit":True,"fit_reason":"배달·케이터링 냉장 배송 필수"},
    {"id":125,"name":"냉동고 정리 바스켓 3종 세트","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":18,"top_reviews":89,"rocket_ratio":21},"selling":19900,"sourcing":3800,"logistics":2500,"weight":"0.8kg","keywords_1688":["冰箱冷冻整理篮 3件","冷冻层收纳","冰箱分类筐"],"customer_fit":True,"fit_reason":"냉동고 식재료 분류 정리 필수"},
    {"id":126,"name":"아이스 버킷 아크릴 투명 3L","related":"업소용 전반","category":"카페용품","channel":"both","competition":{"intensity":22,"top_reviews":123,"rocket_ratio":26},"selling":18900,"sourcing":3800,"logistics":2500,"weight":"0.5kg","keywords_1688":["亚克力冰桶 透明 3L","透明冰桶","冰块容器"],"customer_fit":True,"fit_reason":"음료 제공 시 테이블 얼음 보관용"},
    {"id":127,"name":"식품 온도 기록계 USB 데이터로거","related":"업소용 냉장고","category":"주방소품","channel":"both","competition":{"intensity":37,"top_reviews":278,"rocket_ratio":41},"selling":24900,"sourcing":6000,"logistics":2000,"weight":"0.1kg","keywords_1688":["USB温度记录仪","食品冷链温度计","冷藏温度数据记录"],"customer_fit":True,"fit_reason":"HACCP 냉장 온도 기록 의무화"},

    # ── 배달/포장 전용 ──────────────────────────────────────────────
    {"id":128,"name":"배달 보온백 대형 40L","related":"업소용 전반","category":"배달용품","channel":"coupang","competition":{"intensity":44,"top_reviews":423,"rocket_ratio":48},"selling":34900,"sourcing":8500,"logistics":4000,"weight":"1.2kg","keywords_1688":["外卖保温箱 大号 40L","送餐箱","商用保温袋"],"customer_fit":True,"fit_reason":"배달 업소 필수, 음식 온도 유지"},
    {"id":129,"name":"피자 배달 보온 가방 50cm","related":"업소용 전반","category":"배달용품","channel":"coupang","competition":{"intensity":31,"top_reviews":234,"rocket_ratio":35},"selling":29900,"sourcing":7000,"logistics":3500,"weight":"0.9kg","keywords_1688":["披萨保温袋 50cm","比萨外卖袋","披萨外送保温包"],"customer_fit":True,"fit_reason":"피자 전문점 배달 필수"},
    {"id":130,"name":"배달 음식 밀봉 씰 스티커 500p","related":"업소용 전반","category":"배달용품","channel":"coupang","competition":{"intensity":23,"top_reviews":145,"rocket_ratio":27},"selling":9900,"sourcing":1600,"logistics":1500,"weight":"0.2kg","keywords_1688":["外卖封口贴 500个","打包封口条","食品安全封条"],"customer_fit":True,"fit_reason":"배달 위생·보안 필수 소모품"},
    {"id":131,"name":"크라프트 포장 박스 소형 50p","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":37,"top_reviews":312,"rocket_ratio":41},"selling":14900,"sourcing":3200,"logistics":2500,"weight":"0.8kg","keywords_1688":["牛皮纸外卖盒 小号 50个","环保外卖盒","纸质打包盒"],"customer_fit":True,"fit_reason":"테이크아웃·배달 포장 필수"},
    {"id":132,"name":"일회용 나무 젓가락 100켤레","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":39,"top_reviews":367,"rocket_ratio":43},"selling":9900,"sourcing":1900,"logistics":1500,"weight":"0.4kg","keywords_1688":["一次性木筷子 100双","外卖筷子","卫生竹筷"],"customer_fit":True,"fit_reason":"배달·포장 식당 필수 소모품"},
    {"id":133,"name":"일회용 포크 스푼 세트 100p","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":36,"top_reviews":298,"rocket_ratio":40},"selling":9900,"sourcing":1800,"logistics":1500,"weight":"0.3kg","keywords_1688":["一次性叉勺套装 100套","外卖餐具","塑料叉子勺子"],"customer_fit":True,"fit_reason":"배달 식당 필수 소모품"},
    {"id":134,"name":"테이크아웃 컵 홀더 캐리어 50p","related":"업소용 전반","category":"배달용품","channel":"coupang","competition":{"intensity":26,"top_reviews":178,"rocket_ratio":30},"selling":12900,"sourcing":2300,"logistics":2000,"weight":"0.4kg","keywords_1688":["外卖杯托 50个","奶茶杯架","双杯外卖托"],"customer_fit":True,"fit_reason":"음료 테이크아웃 필수 포장"},

    # ── 홀/인테리어 소품 ─────────────────────────────────────────────
    {"id":135,"name":"업소용 메뉴판 스탠드 A4 아크릴","related":"업소용 전반","category":"홀용품","channel":"coupang","competition":{"intensity":19,"top_reviews":102,"rocket_ratio":22},"selling":16900,"sourcing":3200,"logistics":2000,"weight":"0.3kg","keywords_1688":["菜单台卡 A4 亚克力","桌面菜单架","餐厅菜单展示架"],"customer_fit":True,"fit_reason":"식당 오픈 필수 인테리어 소품"},
    {"id":136,"name":"테이블 클립 메뉴판 홀더 10p","related":"업소용 전반","category":"홀용품","channel":"coupang","competition":{"intensity":14,"top_reviews":67,"rocket_ratio":17},"selling":13900,"sourcing":2200,"logistics":2000,"weight":"0.3kg","keywords_1688":["桌夹菜单夹 10个","台卡夹","菜单夹子"],"customer_fit":True,"fit_reason":"테이블 메뉴 고정 필수"},
    {"id":137,"name":"업소용 벽걸이 화장지 케이스 스텐","related":"업소용 전반","category":"홀용품","channel":"both","competition":{"intensity":17,"top_reviews":89,"rocket_ratio":20},"selling":14900,"sourcing":2600,"logistics":2000,"weight":"0.4kg","keywords_1688":["不锈钢厕纸架 壁挂","卫生间纸架","圆筒纸架"],"customer_fit":True,"fit_reason":"업소 화장실·홀 필수 비품"},
    {"id":138,"name":"냅킨 홀더 스텐 테이블형 5p","related":"업소용 전반","category":"홀용품","channel":"both","competition":{"intensity":16,"top_reviews":78,"rocket_ratio":19},"selling":19900,"sourcing":4000,"logistics":2500,"weight":"0.6kg","keywords_1688":["不锈钢餐巾架 5个","纸巾座","桌面餐巾盒"],"customer_fit":True,"fit_reason":"식당 테이블 필수 비품 세트"},
    {"id":139,"name":"손님 호출 무선 진동 벨 세트","related":"업소용 전반","category":"홀용품","channel":"coupang","competition":{"intensity":42,"top_reviews":378,"rocket_ratio":46},"selling":39900,"sourcing":10000,"logistics":3500,"weight":"0.8kg","keywords_1688":["无线呼叫器套装","餐厅呼叫铃","桌面服务铃"],"customer_fit":True,"fit_reason":"홀 서비스 효율 향상 필수"},
    {"id":140,"name":"포스 영수증 용지 80mm 10롤","related":"업소용 전반","category":"홀용품","channel":"coupang","competition":{"intensity":28,"top_reviews":198,"rocket_ratio":32},"selling":14900,"sourcing":3000,"logistics":2500,"weight":"0.8kg","keywords_1688":["热敏收据纸 80mm 10卷","POS纸","收银纸卷"],"customer_fit":True,"fit_reason":"결제 시스템 필수 소모품"},

    # ── 소독/위생 방역 ──────────────────────────────────────────────
    {"id":141,"name":"무선 충전식 소독 분무기","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":38,"top_reviews":312,"rocket_ratio":42},"selling":29900,"sourcing":7500,"logistics":3000,"weight":"0.6kg","keywords_1688":["无线充电消毒喷雾机","电动喷壶","酒精喷雾器"],"customer_fit":True,"fit_reason":"주방·홀 정기 소독 필수 도구"},
    {"id":142,"name":"손 소독제 자동 센서 디스펜서","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":46,"top_reviews":489,"rocket_ratio":50},"selling":24900,"sourcing":6000,"logistics":2500,"weight":"0.5kg","keywords_1688":["自动感应洗手液机","免接触皂液器","自动消毒器"],"customer_fit":True,"fit_reason":"위생 규정 강화로 업소 필수화"},
    {"id":143,"name":"UV-C 살균 램프 휴대형","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":34,"top_reviews":267,"rocket_ratio":38},"selling":22900,"sourcing":5500,"logistics":2000,"weight":"0.2kg","keywords_1688":["UV-C杀菌灯 便携","紫外线消毒灯","便携消毒棒"],"customer_fit":True,"fit_reason":"조리 도구·표면 살균 필수"},
    {"id":144,"name":"주방 방충 차단 도어 커튼","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":27,"top_reviews":189,"rocket_ratio":31},"selling":18900,"sourcing":4000,"logistics":3000,"weight":"0.7kg","keywords_1688":["厨房防虫门帘","条状门帘","防蝇软门帘"],"customer_fit":True,"fit_reason":"여름철 주방 해충 방지 필수"},
    {"id":145,"name":"주방 UV 해충 퇴치기","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":32,"top_reviews":245,"rocket_ratio":36},"selling":24900,"sourcing":6000,"logistics":2500,"weight":"0.4kg","keywords_1688":["厨房电击灭虫灯","UV诱虫灯","商用灭蚊灯"],"customer_fit":True,"fit_reason":"식품 위생법 해충 관리 필수"},
    {"id":146,"name":"파리 끈끈이 트랩 10p","related":"업소용 전반","category":"위생용품","channel":"coupang","competition":{"intensity":15,"top_reviews":78,"rocket_ratio":18},"selling":8900,"sourcing":1300,"logistics":1500,"weight":"0.1kg","keywords_1688":["粘蝇纸 10个","苍蝇粘纸","灭蝇贴"],"customer_fit":True,"fit_reason":"소모성 방역 소품, 반복 구매"},

    # ── 안전 소품 ────────────────────────────────────────────────────
    {"id":147,"name":"미끄럼 방지 안전 테이프 5m 황색","related":"업소용 전반","category":"안전용품","channel":"both","competition":{"intensity":16,"top_reviews":78,"rocket_ratio":19},"selling":11900,"sourcing":1800,"logistics":1500,"weight":"0.2kg","keywords_1688":["防滑警示胶带 5m 黄色","地面防滑条","安全警示贴"],"customer_fit":True,"fit_reason":"주방 바닥 안전사고 방지 필수"},
    {"id":148,"name":"절단 방지 스텐 와이어 장갑 1p","related":"업소용 작업대","category":"안전용품","channel":"both","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":26},"selling":14900,"sourcing":2800,"logistics":2000,"weight":"0.15kg","keywords_1688":["防切割手套 不锈钢","钢丝手套","切肉防护手套"],"customer_fit":True,"fit_reason":"육류 손질 시 절단 사고 방지 필수"},
    {"id":149,"name":"실리콘 화상 방지 오븐 장갑 1p","related":"업소용 오븐","category":"안전용품","channel":"both","competition":{"intensity":33,"top_reviews":256,"rocket_ratio":37},"selling":16900,"sourcing":3200,"logistics":2000,"weight":"0.3kg","keywords_1688":["硅胶隔热手套","防烫烤箱手套","耐高温烹饪手套"],"customer_fit":True,"fit_reason":"오븐·솥 사용 시 화상 방지 필수"},
    {"id":150,"name":"가스 누출 감지기 디지털","related":"업소용 가스레인지","category":"안전용품","channel":"both","competition":{"intensity":39,"top_reviews":312,"rocket_ratio":43},"selling":24900,"sourcing":6000,"logistics":2000,"weight":"0.2kg","keywords_1688":["燃气泄漏报警器","煤气探测器","天然气报警器"],"customer_fit":True,"fit_reason":"가스레인지 사용 업소 안전 필수"},

    # ── 냄비/프라이팬 세트 ──────────────────────────────────────────
    {"id":151,"name":"업소용 스텐 냄비 3종 16/18/20cm","related":"업소용 가스레인지","category":"조리도구","channel":"coupang","competition":{"intensity":41,"top_reviews":389,"rocket_ratio":45},"selling":44900,"sourcing":11000,"logistics":4500,"weight":"2.5kg","keywords_1688":["不锈钢汤锅3件套 16 18 20","商用奶锅","厨房锅具套装"],"customer_fit":True,"fit_reason":"식당 오픈 시 필수 냄비 세트"},
    {"id":152,"name":"업소용 프라이팬 3종 세트 26/28/30cm","related":"업소용 가스레인지","category":"조리도구","channel":"coupang","competition":{"intensity":48,"top_reviews":512,"rocket_ratio":52},"selling":49900,"sourcing":13000,"logistics":5000,"weight":"3.0kg","keywords_1688":["不粘炒锅3件套 26 28 30","商用平底锅","厨房炒菜锅"],"customer_fit":True,"fit_reason":"업소 오픈 필수 프라이팬 세트"},
    {"id":153,"name":"업소용 뚝배기 세트 2종 대/소","related":"업소용 가스레인지","category":"조리도구","channel":"coupang","competition":{"intensity":27,"top_reviews":178,"rocket_ratio":31},"selling":24900,"sourcing":6000,"logistics":3500,"weight":"1.8kg","keywords_1688":["砂锅套装 大小","韩式石锅","陶瓷砂锅2件"],"customer_fit":True,"fit_reason":"한식당 뚝배기 요리 필수"},
    {"id":154,"name":"돌솥 비빔밥 그릇 소형 5p","related":"업소용 가스레인지","category":"식기류","channel":"coupang","competition":{"intensity":23,"top_reviews":145,"rocket_ratio":27},"selling":34900,"sourcing":8500,"logistics":4000,"weight":"2.0kg","keywords_1688":["石锅拌饭碗 小号 5个","韩式石碗","石锅 餐厅"],"customer_fit":True,"fit_reason":"비빔밥 전문점 필수 용기"},
    {"id":155,"name":"업소용 전골 냄비 인덕션 28cm","related":"업소용 가스레인지","category":"조리도구","channel":"coupang","competition":{"intensity":34,"top_reviews":267,"rocket_ratio":38},"selling":39900,"sourcing":9500,"logistics":4000,"weight":"2.2kg","keywords_1688":["火锅锅具 电磁炉 28cm","韩式火锅","不粘涮肉锅"],"customer_fit":True,"fit_reason":"삼겹살·전골 업소 필수"},

    # ── 자동화/편의 도구 ─────────────────────────────────────────────
    {"id":156,"name":"자동 계란 삶기 기계 6구","related":"업소용 가스레인지","category":"주방기기","channel":"both","competition":{"intensity":29,"top_reviews":212,"rocket_ratio":33},"selling":24900,"sourcing":6000,"logistics":3000,"weight":"0.6kg","keywords_1688":["自动煮蛋器 6个","蒸蛋机","鸡蛋蒸煮器"],"customer_fit":True,"fit_reason":"달걀 요리 업소 시간 절약 필수"},
    {"id":157,"name":"전동 채소 슬라이서 소형","related":"업소용 작업대","category":"주방기기","channel":"coupang","competition":{"intensity":43,"top_reviews":398,"rocket_ratio":47},"selling":49900,"sourcing":13000,"logistics":4000,"weight":"1.5kg","keywords_1688":["电动切菜机 小型","商用切片机","蔬菜电动刨丝机"],"customer_fit":True,"fit_reason":"채소 손질 시간 대폭 절약"},
    {"id":158,"name":"전기 핫플레이트 1구 소형","related":"업소용 가스레인지","category":"주방기기","channel":"coupang","competition":{"intensity":37,"top_reviews":289,"rocket_ratio":41},"selling":34900,"sourcing":9000,"logistics":4000,"weight":"1.8kg","keywords_1688":["单口电热炉","小型电磁炉","迷你电热板"],"customer_fit":True,"fit_reason":"가스 없는 공간 임시 조리 필수"},
    {"id":159,"name":"전기 만두찜기 2단","related":"업소용 가스레인지","category":"주방기기","channel":"coupang","competition":{"intensity":31,"top_reviews":245,"rocket_ratio":35},"selling":39900,"sourcing":10000,"logistics":4000,"weight":"2.0kg","keywords_1688":["电蒸锅 双层","电动蒸饺机","商用蒸饺炉"],"customer_fit":True,"fit_reason":"분식·만두 전문점 필수 기기"},
    {"id":160,"name":"오렌지 자동 주스 착즙기","related":"업소용 전반","category":"주방기기","channel":"coupang","competition":{"intensity":36,"top_reviews":278,"rocket_ratio":40},"selling":44900,"sourcing":12000,"logistics":4500,"weight":"2.5kg","keywords_1688":["自动榨橙汁机","商用鲜榨果汁机","电动橙汁压榨机"],"customer_fit":True,"fit_reason":"카페·레스토랑 생과일주스 필수"},

    # ── 작업대/선반 액세서리 ─────────────────────────────────────────
    {"id":161,"name":"주방 행거 봉 후크 세트 60cm","related":"업소용 작업대","category":"수납/정리","channel":"both","competition":{"intensity":21,"top_reviews":123,"rocket_ratio":25},"selling":19900,"sourcing":4200,"logistics":2500,"weight":"0.7kg","keywords_1688":["厨房挂杆 钩子套装 60cm","厨具挂架","壁挂横杆"],"customer_fit":True,"fit_reason":"작업대 주변 도구 정리 효율화"},
    {"id":162,"name":"벽부착 선반 조합 세트 40cm","related":"업소용 작업대","category":"수납/정리","channel":"both","competition":{"intensity":33,"top_reviews":256,"rocket_ratio":37},"selling":24900,"sourcing":5500,"logistics":3000,"weight":"1.0kg","keywords_1688":["壁挂搁板组合 40cm","浮动墙架","厨房挂板"],"customer_fit":True,"fit_reason":"주방 벽 수납 공간 최대화"},
    {"id":163,"name":"주방 방수 멀티탭 6구","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":38,"top_reviews":312,"rocket_ratio":42},"selling":22900,"sourcing":5200,"logistics":2500,"weight":"0.5kg","keywords_1688":["厨房防水排插 6孔","防水插座","厨房多功能插线板"],"customer_fit":True,"fit_reason":"주방 전기기기 연결 필수"},
    {"id":164,"name":"업소용 고무 발받침 8p 세트","related":"업소용 작업대","category":"주방소품","channel":"both","competition":{"intensity":11,"top_reviews":45,"rocket_ratio":14},"selling":8900,"sourcing":1000,"logistics":1500,"weight":"0.1kg","keywords_1688":["橡胶防滑垫脚 8个","家具减震脚垫","桌脚保护垫"],"customer_fit":True,"fit_reason":"작업대·선반 바닥 긁힘 방지 필수"},
    {"id":165,"name":"스텐 작업대 보호 코너 가드 8p","related":"업소용 작업대","category":"안전용품","channel":"both","competition":{"intensity":14,"top_reviews":56,"rocket_ratio":17},"selling":11900,"sourcing":1700,"logistics":1500,"weight":"0.2kg","keywords_1688":["不锈钢桌角保护套 8个","台面护角","防碰角套"],"customer_fit":True,"fit_reason":"작업대 모서리 안전 보호"},

    # ── 스마트/디지털 소품 ──────────────────────────────────────────
    {"id":166,"name":"냉장고 온도 이탈 알림 센서","related":"업소용 냉장고","category":"주방소품","channel":"both","competition":{"intensity":29,"top_reviews":189,"rocket_ratio":33},"selling":19900,"sourcing":4500,"logistics":2000,"weight":"0.1kg","keywords_1688":["冰箱温度报警传感器","温度异常报警","冷藏温控传感"],"customer_fit":True,"fit_reason":"HACCP 냉장 온도 이탈 즉시 감지"},
    {"id":167,"name":"주방 공기질 모니터 소형","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":35,"top_reviews":267,"rocket_ratio":39},"selling":34900,"sourcing":9000,"logistics":2500,"weight":"0.2kg","keywords_1688":["厨房空气质量检测仪","CO2传感器","厨房空气监测"],"customer_fit":True,"fit_reason":"주방 환기 관리 및 화재 예방"},
    {"id":168,"name":"주방 화이트보드 냉장고 부착형","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":17,"top_reviews":89,"rocket_ratio":20},"selling":12900,"sourcing":2200,"logistics":2000,"weight":"0.3kg","keywords_1688":["冰箱磁性白板","冰箱贴白板","厨房备忘板"],"customer_fit":True,"fit_reason":"일별 메뉴·재고 관리 필수"},
    {"id":169,"name":"식재료 구매 접이식 장바구니 대형","related":"업소용 전반","category":"수납/정리","channel":"both","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":26},"selling":16900,"sourcing":3200,"logistics":2500,"weight":"0.5kg","keywords_1688":["可折叠购物篮 大号","超市购物车","折叠菜篮"],"customer_fit":True,"fit_reason":"식재료 구매·운반 효율 향상"},
    {"id":170,"name":"업소용 영수증 보관 바인더 A4","related":"업소용 전반","category":"주방소품","channel":"coupang","competition":{"intensity":13,"top_reviews":56,"rocket_ratio":16},"selling":11900,"sourcing":1800,"logistics":1500,"weight":"0.3kg","keywords_1688":["收据整理文件夹 A4","会计凭证夹","发票保存夹"],"customer_fit":True,"fit_reason":"세금계산서·납품서 보관 필수"},

    # ── 주방 소독/세척 기기 ─────────────────────────────────────────
    {"id":171,"name":"업소용 고압 세척기 소형 (가정겸용)","related":"업소용 전반","category":"주방기기","channel":"coupang","competition":{"intensity":48,"top_reviews":512,"rocket_ratio":52},"selling":49900,"sourcing":14000,"logistics":5000,"weight":"3.5kg","keywords_1688":["高压清洗机 小型","家用洗车机","商用清洁机"],"customer_fit":True,"fit_reason":"주방 바닥·장비 세척 필수"},
    {"id":172,"name":"스텀 스팀 청소기 소형 업소용","related":"업소용 전반","category":"주방기기","channel":"coupang","competition":{"intensity":42,"top_reviews":389,"rocket_ratio":46},"selling":39900,"sourcing":11000,"logistics":4000,"weight":"2.0kg","keywords_1688":["蒸汽清洁机 小型","手持蒸汽枪","商用蒸汽消毒机"],"customer_fit":True,"fit_reason":"주방 기름때·살균 동시 처리"},
    {"id":173,"name":"세척 솔 다용도 세트 5종","related":"업소용 싱크대","category":"위생용품","channel":"both","competition":{"intensity":18,"top_reviews":98,"rocket_ratio":21},"selling":14900,"sourcing":2600,"logistics":2000,"weight":"0.4kg","keywords_1688":["多功能清洗刷套装 5件","厨房清洁刷组合","洗碗刷套装"],"customer_fit":True,"fit_reason":"주방 기기별 맞춤 세척 필수"},

    # ── 환경/에코 소품 ──────────────────────────────────────────────
    {"id":174,"name":"폐식용유 수거 전용 통 10L","related":"업소용 가스레인지","category":"환경용품","channel":"both","competition":{"intensity":14,"top_reviews":56,"rocket_ratio":17},"selling":19900,"sourcing":3800,"logistics":3000,"weight":"0.8kg","keywords_1688":["废食用油收集桶 10L","餐厅废油桶","厨房废弃油罐"],"customer_fit":True,"fit_reason":"식용유 수거 의무화 법규 대응"},
    {"id":175,"name":"재활용 분리수거 소형 세트 3종","related":"업소용 전반","category":"환경용품","channel":"both","competition":{"intensity":26,"top_reviews":178,"rocket_ratio":30},"selling":22900,"sourcing":5200,"logistics":3500,"weight":"1.5kg","keywords_1688":["分类垃圾桶 3件套","回收垃圾桶","厨房垃圾分类"],"customer_fit":True,"fit_reason":"분리수거 의무화 대응 필수"},
    {"id":176,"name":"음식물 쓰레기통 자동 밀봉형","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":33,"top_reviews":245,"rocket_ratio":37},"selling":24900,"sourcing":6000,"logistics":3500,"weight":"1.2kg","keywords_1688":["全自动密封垃圾桶","电动垃圾桶","自动封口厨房桶"],"customer_fit":True,"fit_reason":"주방 악취 방지 위생 필수"},
    {"id":177,"name":"주방 타일 기름 방지 방수 시트 5p","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":19,"top_reviews":102,"rocket_ratio":22},"selling":14900,"sourcing":2600,"logistics":2000,"weight":"0.3kg","keywords_1688":["厨房防油贴纸 5张","防溅油贴","瓷砖防污贴"],"customer_fit":True,"fit_reason":"주방 벽 타일 청소 편의성 향상"},

    # ── 식재료 관리 도구 ─────────────────────────────────────────────
    {"id":178,"name":"식품 유통기한 스캐너 소형","related":"업소용 냉장고","category":"주방기기","channel":"coupang","competition":{"intensity":31,"top_reviews":234,"rocket_ratio":35},"selling":29900,"sourcing":7500,"logistics":2500,"weight":"0.15kg","keywords_1688":["食品条形码扫描仪","手持条码枪","库存管理扫描器"],"customer_fit":True,"fit_reason":"HACCP 식품 관리 자동화 필수"},
    {"id":179,"name":"식재료 보관 색상 구분 클립 30p","related":"업소용 냉장고","category":"위생용품","channel":"both","competition":{"intensity":9,"top_reviews":34,"rocket_ratio":12},"selling":8900,"sourcing":1000,"logistics":1500,"weight":"0.1kg","keywords_1688":["彩色食品袋夹 30个","分色密封夹","HACCP颜色管理夹"],"customer_fit":True,"fit_reason":"HACCP 색상 관리 필수 소모품"},
    {"id":180,"name":"업소용 계량 디지털 저울 30kg","related":"업소용 전반","category":"주방소품","channel":"coupang","competition":{"intensity":36,"top_reviews":278,"rocket_ratio":40},"selling":34900,"sourcing":9000,"logistics":4000,"weight":"1.5kg","keywords_1688":["厨房电子秤 30kg","商用大量程称","食材称重秤"],"customer_fit":True,"fit_reason":"대량 식재료 계량 필수 도구"},

    # ── 조명/인테리어 ───────────────────────────────────────────────
    {"id":181,"name":"주방 LED 조명 형광등 교체형 60cm","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":44,"top_reviews":423,"rocket_ratio":48},"selling":24900,"sourcing":6500,"logistics":3500,"weight":"0.5kg","keywords_1688":["厨房LED灯管 60cm","T8 LED灯","商用荧光灯替换"],"customer_fit":True,"fit_reason":"주방 조명 교체 필수, 고회전 소모품"},
    {"id":182,"name":"주방 방수 시계 벽걸이형","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":21,"top_reviews":134,"rocket_ratio":24},"selling":16900,"sourcing":3400,"logistics":2000,"weight":"0.3kg","keywords_1688":["厨房防水壁挂钟","防水时钟","厨房专用挂钟"],"customer_fit":True,"fit_reason":"주방 시간 관리 필수"},
    {"id":183,"name":"업소용 방수 블루투스 스피커","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":47,"top_reviews":489,"rocket_ratio":51},"selling":29900,"sourcing":7500,"logistics":2500,"weight":"0.4kg","keywords_1688":["防水蓝牙音箱","浴室无线音响","厨房蓝牙喇叭"],"customer_fit":True,"fit_reason":"주방 분위기 조성 및 직원 사기 향상"},

    # ── 청결/정리 기타 ──────────────────────────────────────────────
    {"id":184,"name":"업소용 종이타월 티슈 대형 4롤","related":"업소용 전반","category":"위생용품","channel":"coupang","competition":{"intensity":39,"top_reviews":356,"rocket_ratio":43},"selling":12900,"sourcing":2800,"logistics":2500,"weight":"1.2kg","keywords_1688":["厨房纸巾卷 大号 4卷","商用擦手纸","厨房用纸"],"customer_fit":True,"fit_reason":"주방 위생 청결 필수 소모품"},
    {"id":185,"name":"주방 악취 제거 활성탄 필터 3p","related":"업소용 전반","category":"위생용품","channel":"both","competition":{"intensity":17,"top_reviews":89,"rocket_ratio":20},"selling":12900,"sourcing":2200,"logistics":2000,"weight":"0.3kg","keywords_1688":["厨房活性炭除臭剂 3个","环境除味碳包","冰箱除味剂"],"customer_fit":True,"fit_reason":"주방·냉장고 악취 제거 필수"},
    {"id":186,"name":"업소용 고무줄 대형 200p","related":"업소용 전반","category":"포장용품","channel":"coupang","competition":{"intensity":11,"top_reviews":45,"rocket_ratio":14},"selling":7900,"sourcing":900,"logistics":1500,"weight":"0.2kg","keywords_1688":["橡皮筋 大号 200个","捆扎用橡皮筋","食品捆绑弹力绳"],"customer_fit":True,"fit_reason":"식재료 묶음 관리 필수 소모품"},
    {"id":187,"name":"접이식 사다리 발판 2단","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":38,"top_reviews":312,"rocket_ratio":42},"selling":29900,"sourcing":7500,"logistics":4000,"weight":"2.5kg","keywords_1688":["折叠踏脚梯 2步","折叠人字梯","厨房矮梯"],"customer_fit":True,"fit_reason":"높은 선반 사용 시 필수 안전 도구"},
    {"id":188,"name":"업소용 방수 앞치마 반형 (허리)","related":"업소용 전반","category":"주방 의류","channel":"coupang","competition":{"intensity":29,"top_reviews":198,"rocket_ratio":33},"selling":12900,"sourcing":2300,"logistics":2000,"weight":"0.2kg","keywords_1688":["防水半身围裙","厨房腰围裙","短款防油围裙"],"customer_fit":True,"fit_reason":"홀 서빙 직원용 앞치마"},
    {"id":189,"name":"업소용 셰프 모자 (면) 5p","related":"업소용 전반","category":"주방 의류","channel":"coupang","competition":{"intensity":16,"top_reviews":78,"rocket_ratio":19},"selling":14900,"sourcing":2600,"logistics":2000,"weight":"0.2kg","keywords_1688":["棉厨师帽 5个","厨师帽白色","炊事帽"],"customer_fit":True,"fit_reason":"위생 규정 필수, 재사용 셰프 모자"},
    {"id":190,"name":"업소용 안전화 미끄럼방지 주방용","related":"업소용 전반","category":"안전용품","channel":"coupang","competition":{"intensity":45,"top_reviews":467,"rocket_ratio":49},"selling":39900,"sourcing":10000,"logistics":4000,"weight":"0.8kg","keywords_1688":["厨房防滑鞋","防水工作鞋","餐厅防滑安全鞋"],"customer_fit":True,"fit_reason":"주방 안전사고 예방 필수 안전화"},

    # ── 잡화/기타 ───────────────────────────────────────────────────
    {"id":191,"name":"업소용 가위 다용도 스텐 (주방용)","related":"업소용 전반","category":"조리도구","channel":"both","competition":{"intensity":26,"top_reviews":178,"rocket_ratio":30},"selling":12900,"sourcing":2000,"logistics":1500,"weight":"0.15kg","keywords_1688":["厨房不锈钢剪刀","多功能厨剪","料理剪刀"],"customer_fit":True,"fit_reason":"주방 필수 도구, 소모성 교체 품목"},
    {"id":192,"name":"업소용 오프너 다기능 (캔/병/뚜껑)","related":"업소용 전반","category":"조리도구","channel":"both","competition":{"intensity":14,"top_reviews":67,"rocket_ratio":17},"selling":11900,"sourcing":1800,"logistics":1500,"weight":"0.15kg","keywords_1688":["多功能开瓶器","开罐器 开瓶盖","厨房开启工具"],"customer_fit":True,"fit_reason":"다양한 용기 개봉 필수 도구"},
    {"id":193,"name":"주방 내열 유리 용기 5종 세트","related":"업소용 냉장고","category":"냉장고 용품","channel":"both","competition":{"intensity":37,"top_reviews":298,"rocket_ratio":41},"selling":29900,"sourcing":7500,"logistics":3500,"weight":"1.5kg","keywords_1688":["耐热玻璃容器 5件套","钢化玻璃保鲜盒","微波炉玻璃盒"],"customer_fit":True,"fit_reason":"전자레인지·오븐 겸용 보관 용기"},
    {"id":194,"name":"업소용 소형 저울 500g (정밀)","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":22,"top_reviews":134,"rocket_ratio":26},"selling":16900,"sourcing":3500,"logistics":2000,"weight":"0.2kg","keywords_1688":["精密电子秤 500g","烘焙克重秤","0.1g精准称"],"customer_fit":True,"fit_reason":"제과·커피 정밀 계량 필수"},
    {"id":195,"name":"보온 런치백 접이식 대형","related":"업소용 전반","category":"배달용품","channel":"both","competition":{"intensity":31,"top_reviews":234,"rocket_ratio":35},"selling":19900,"sourcing":4500,"logistics":2500,"weight":"0.5kg","keywords_1688":["保温午餐袋 大号 折叠","隔热饭盒袋","便携保温包"],"customer_fit":True,"fit_reason":"직원 도시락·배달 식품 보온 필수"},
    {"id":196,"name":"주방 세제 소분 용기 세트 4종","related":"업소용 싱크대","category":"싱크대 용품","channel":"both","competition":{"intensity":16,"top_reviews":78,"rocket_ratio":19},"selling":13900,"sourcing":2500,"logistics":2000,"weight":"0.4kg","keywords_1688":["洗洁精分装瓶 4件","洗涤剂喷瓶","厨房清洁剂容器"],"customer_fit":True,"fit_reason":"대용량 세제 소분 관리 필수"},
    {"id":197,"name":"업소용 작업 장갑 니트릴 L 50p","related":"업소용 전반","category":"위생용품","channel":"coupang","competition":{"intensity":42,"top_reviews":389,"rocket_ratio":46},"selling":14900,"sourcing":3200,"logistics":2000,"weight":"0.3kg","keywords_1688":["丁腈手套 L 50双","一次性丁腈手套","食品检查手套"],"customer_fit":True,"fit_reason":"내구성 높은 일회용 장갑 소모품"},
    {"id":198,"name":"냉장고 자석 오더 메모 패드 3p","related":"업소용 전반","category":"주방소품","channel":"both","competition":{"intensity":11,"top_reviews":45,"rocket_ratio":14},"selling":9900,"sourcing":1300,"logistics":1500,"weight":"0.1kg","keywords_1688":["冰箱磁性记事本 3本","冰箱贴便签","磁贴便条纸"],"customer_fit":True,"fit_reason":"주방 오더·메모 관리 필수"},
    {"id":199,"name":"업소용 스텐 보온 도시락 2단","related":"업소용 전반","category":"식기류","channel":"coupang","competition":{"intensity":28,"top_reviews":198,"rocket_ratio":32},"selling":22900,"sourcing":5500,"logistics":3000,"weight":"0.7kg","keywords_1688":["不锈钢保温饭盒 双层","保温便当盒","真空保温餐盒"],"customer_fit":True,"fit_reason":"직원 식사·배달 보온 필수"},
    {"id":200,"name":"업소용 위생 손 건조기 벽부착","related":"업소용 전반","category":"위생용품","channel":"coupang","competition":{"intensity":44,"top_reviews":423,"rocket_ratio":48},"selling":49900,"sourcing":14000,"logistics":4000,"weight":"1.5kg","keywords_1688":["壁挂烘手器","自动干手机","商用风干机"],"customer_fit":True,"fit_reason":"위생 시설 의무화, 손 세척 후 필수"},
]
